/**
 * Reward Shop. Rewards are the player's own real-life rewards, bought with
 * earned GP only. Redemption is atomic: validate → deduct GP (guarded, never
 * negative) → record the redemption → ledger transaction → success state.
 * A client request id makes a double-submitted redemption a no-op.
 */

import { and, desc, eq, sql } from "drizzle-orm";
import { REWARD_TEMPLATES } from "@/game/content/reward-templates";
import { GameRuleError } from "@/game/errors";
import { validateReward, type RewardInput } from "@/game/rewards";
import type { Db } from "../db/client";
import { activityEvents, characters, progressionTransactions, rewardRedemptions, rewards, type RewardRow } from "../db/schema";
import { spendGp } from "../progression/service";

export class RewardNotFoundError extends GameRuleError {
  constructor() {
    super("That reward could not be found.", "REWARD_NOT_FOUND");
  }
}

async function ownReward(db: Db, characterId: string, rewardId: string, lock = false): Promise<RewardRow> {
  const q = db.select().from(rewards).where(and(eq(rewards.id, rewardId), eq(rewards.characterId, characterId)));
  const [row] = lock ? await q.for("update") : await q;
  if (!row) throw new RewardNotFoundError();
  return row;
}

export async function createReward(db: Db, characterId: string, input: RewardInput) {
  const clean = validateReward(input);
  const [count] = await db.select({ n: sql<number>`count(*)::int` }).from(rewards).where(eq(rewards.characterId, characterId));
  if (count.n >= 200) throw new GameRuleError("Your Reward Shop is full. Archive or remove a reward first.", "REWARD_LIMIT");
  const [row] = await db.insert(rewards).values({ characterId, ...clean }).returning();
  return row;
}

export async function addRewardFromTemplate(db: Db, characterId: string, templateKey: string) {
  const t = REWARD_TEMPLATES.find((r) => r.key === templateKey);
  if (!t) throw new GameRuleError("That reward idea is no longer available.", "REWARD_TEMPLATE_NOT_FOUND");
  return createReward(db, characterId, { name: t.name, description: t.description, category: t.category, icon: t.icon, gpCost: t.gpCost, repeatable: t.repeatable });
}

/** Editing a reward never changes past redemptions (they snapshot name and cost). */
export async function updateReward(db: Db, characterId: string, rewardId: string, input: RewardInput) {
  const clean = validateReward(input);
  await ownReward(db, characterId, rewardId);
  const [row] = await db.update(rewards).set(clean).where(eq(rewards.id, rewardId)).returning();
  return row;
}

export async function setRewardActive(db: Db, characterId: string, rewardId: string, active: boolean) {
  await ownReward(db, characterId, rewardId);
  await db.update(rewards).set({ active }).where(eq(rewards.id, rewardId));
}

/** Remove a reward that was never redeemed. Redeemed rewards are archived instead, keeping history. */
export async function removeReward(db: Db, characterId: string, rewardId: string) {
  return db.transaction(async (tx) => {
    await ownReward(tx, characterId, rewardId, true);
    const [used] = await tx.select({ id: rewardRedemptions.id }).from(rewardRedemptions).where(eq(rewardRedemptions.rewardId, rewardId)).limit(1);
    if (used) {
      await tx.update(rewards).set({ active: false }).where(eq(rewards.id, rewardId));
      return { archived: true };
    }
    await tx.delete(rewards).where(eq(rewards.id, rewardId));
    return { archived: false };
  });
}

export type Redemption = {
  duplicate: boolean;
  redemptionId: string;
  rewardName: string;
  gpCost: number;
  gpBalance: number;
};

/**
 * Redeem a reward. `requestId` (generated by the client per confirmation)
 * makes retries and double clicks safe: the same request never spends twice.
 */
export async function redeemReward(db: Db, characterId: string, rewardId: string, requestId: string): Promise<Redemption> {
  if (!/^[A-Za-z0-9-]{8,64}$/.test(requestId)) throw new GameRuleError("The redemption request was malformed. Try again.", "BAD_REQUEST_ID");
  return db.transaction(async (tx) => {
    const key = `redeem:${requestId}`;
    const [prior] = await tx
      .select()
      .from(progressionTransactions)
      .where(and(eq(progressionTransactions.characterId, characterId), eq(progressionTransactions.idempotencyKey, key)));
    if (prior) {
      const [c] = await tx.select({ gp: characters.gpBalance }).from(characters).where(eq(characters.id, characterId));
      const meta = prior.metadata as { redemptionId: string; rewardName: string };
      return { duplicate: true, redemptionId: meta.redemptionId, rewardName: meta.rewardName, gpCost: -prior.amount, gpBalance: c.gp };
    }

    // 1. Validate.
    const reward = await ownReward(tx, characterId, rewardId, true);
    if (!reward.active) throw new GameRuleError("This reward is archived. Restore it to redeem it.", "REWARD_ARCHIVED");
    if (!reward.repeatable) {
      const [used] = await tx.select({ id: rewardRedemptions.id }).from(rewardRedemptions).where(eq(rewardRedemptions.rewardId, rewardId)).limit(1);
      if (used) throw new GameRuleError("This one-time reward has already been claimed.", "REWARD_ALREADY_CLAIMED");
    }
    // 2–3. Record the redemption, then deduct GP (guarded update; throws if short).
    const [redemption] = await tx
      .insert(rewardRedemptions)
      .values({ rewardId, characterId, gpCostSnapshot: reward.gpCost, rewardNameSnapshot: reward.name })
      .returning();
    // 4. Ledger transaction (the spend itself).
    await spendGp(tx, characterId, reward.gpCost, {
      sourceType: "REWARD_REDEMPTION",
      sourceId: redemption.id,
      idempotencyKey: key,
      metadata: { redemptionId: redemption.id, rewardId, rewardName: reward.name },
    });
    if (!reward.repeatable) await tx.update(rewards).set({ active: false }).where(eq(rewards.id, rewardId));
    await tx.insert(activityEvents).values({
      characterId,
      type: "REWARD_REDEEMED",
      entityId: redemption.id,
      payload: { name: reward.name, gpCost: reward.gpCost },
    });
    const [c] = await tx.select({ gp: characters.gpBalance }).from(characters).where(eq(characters.id, characterId));
    // 5. Success state.
    return { duplicate: false, redemptionId: redemption.id, rewardName: reward.name, gpCost: reward.gpCost, gpBalance: c.gp };
  });
}

export async function getRewardShop(db: Db, characterId: string) {
  const [list, history, [c]] = await Promise.all([
    db.select().from(rewards).where(eq(rewards.characterId, characterId)).orderBy(rewards.gpCost, rewards.createdAt),
    db.select().from(rewardRedemptions).where(eq(rewardRedemptions.characterId, characterId)).orderBy(desc(rewardRedemptions.redeemedAt)).limit(100),
    db
      .select({ gpBalance: characters.gpBalance, lifetimeGpEarned: characters.lifetimeGpEarned, lifetimeGpSpent: characters.lifetimeGpSpent })
      .from(characters)
      .where(eq(characters.id, characterId)),
  ]);
  const timesRedeemed = new Map<string, number>();
  const [counts] = [
    await db
      .select({ rewardId: rewardRedemptions.rewardId, n: sql<number>`count(*)::int` })
      .from(rewardRedemptions)
      .where(eq(rewardRedemptions.characterId, characterId))
      .groupBy(rewardRedemptions.rewardId),
  ];
  for (const r of counts) timesRedeemed.set(r.rewardId, r.n);
  const owned = new Set(list.map((r) => r.name.toLowerCase()));
  return {
    balance: c,
    rewards: list.map((r) => ({ ...r, timesRedeemed: timesRedeemed.get(r.id) ?? 0 })),
    history,
    templates: REWARD_TEMPLATES.filter((t) => !owned.has(t.name.toLowerCase())),
  };
}
