/**
 * Questly pixel-art sprite sheet — original artwork, drawn as 16×16 grids.
 * Each character maps to a design-token color in SPRITE_PALETTE; "." is clear.
 * Keep every row exactly 16 characters (enforced by sprites.test.ts).
 */

export const SPRITE_PALETTE: Record<string, string> = {
  K: "var(--color-border-dark)",
  g: "var(--color-gold-600)",
  G: "var(--color-gold-400)",
  Y: "var(--color-gold-200)",
  b: "var(--color-timber-800)",
  w: "var(--color-timber-600)",
  W: "var(--color-timber-500)",
  d: "var(--color-stone-800)",
  s: "var(--color-stone-700)",
  L: "var(--color-stone-600)",
  S: "var(--color-stone-500)",
  i: "var(--color-text-secondary)",
  I: "var(--color-text-primary)",
  p: "var(--color-parchment-200)",
  P: "var(--color-parchment-50)",
  q: "var(--color-parchment-400)",
  k: "var(--color-parchment-ink)",
  m: "var(--color-moss-500)",
  M: "var(--color-moss-300)",
  n: "var(--color-moss-700)",
  t: "var(--color-teal-500)",
  T: "var(--color-teal-300)",
  c: "var(--color-teal-700)",
  r: "var(--color-crimson-500)",
  R: "var(--color-crimson-300)",
  x: "var(--color-crimson-700)",
  u: "var(--color-blue-500)",
  U: "var(--color-blue-300)",
};

export const SPRITES = {
  world: [
    ".....KKKKKK.....",
    "...KKttttttKK...",
    "..KtMMtttttttK..",
    ".KtMMMmtttMMttK.",
    ".KtMMmmtttMmmtK.",
    "KttMmmtttttmmttK",
    "KtttmttttttttttK",
    "KtttttMMMtttttcK",
    "KttttMMmmmttttcK",
    "KttttMmmmmmtttcK",
    "KtttttmmmmttttcK",
    ".KtttttmmtttttK.",
    ".KcttttttttttcK.",
    "..KccttttttccK..",
    "...KKccccccKK...",
    ".....KKKKKK.....",
  ],
  quests: [
    "................",
    "..KKKKKKKKKKKK..",
    ".KqPPPPPPPPPPqK.",
    ".KKKKKKKKKKKKKK.",
    "..KPPPPPPPPPPK..",
    "..KPkkkkkkkPPK..",
    "..KPPPPPPPPPPK..",
    "..KPkkkkkkPPPK..",
    "..KPPPPPPPPPPK..",
    "..KPkkkkkkkkPK..",
    "..KPPPPPPPPPPK..",
    "..KPkkkkkPPrrK..",
    ".KKKKKKKKKKrRK..",
    ".KqPPPPPPPPKrK..",
    "..KKKKKKKKKKK...",
    "................",
  ],
  combat: [
    "KK............KK",
    "KIK..........KIK",
    ".KIK........KIK.",
    "..KIK......KIK..",
    "...KIK....KIK...",
    "....KIK..KIK....",
    ".....KIKKIK.....",
    "......KIIK......",
    "......KIIK......",
    ".....KIKKIK.....",
    "..KKKIK..KIKKK..",
    "..KGGKK..KKGGK..",
    "...KwK....KwK...",
    "..KwK......KwK..",
    ".KGK........KGK.",
    ".KK..........KK.",
  ],
  collection: [
    "................",
    "...KKKKKKKKKK...",
    "..KwWWWWWWWWwK..",
    ".KwWWWWWWWWWWwK.",
    ".KGKKKKKKKKKKGK.",
    ".KGwwwwwwwwwwGK.",
    "KKKKKKKKKKKKKKKK",
    "KGgggggKKgggggGK",
    "KwwwwwKYGKwwwwwK",
    "KwwwwwKGgKwwwwwK",
    "KwwwwwwKKwwwwwwK",
    "KGwwwwwwwwwwwwGK",
    "KGbbbbbbbbbbbbGK",
    "KKKKKKKKKKKKKKKK",
    "................",
    "................",
  ],
  shop: [
    "................",
    "......KKKK......",
    ".....KbwwbK.....",
    "......KrrK......",
    ".....KKrrKK.....",
    "....KwWWWWwK....",
    "...KwWWWWWWwK...",
    "..KwWWWKKWWWwK..",
    "..KwWWKYGKWWwK..",
    ".KwWWWKGgKWWWwK.",
    ".KwWWWWKKWWWWwK.",
    ".KwWWWWWWWWWWwK.",
    ".KbwWWWWWWWWwbK.",
    "..KbbwwwwwwbbK..",
    "...KKKKKKKKKK...",
    "................",
  ],
  character: [
    "................",
    ".....KKKKKK.....",
    "....KSiiiiSK....",
    "...KSiSSSSiSK...",
    "..KSiSSSSSSSsK..",
    "..KSSSSSSSSSsK..",
    "..KSKKKKKKKKsK..",
    "..KSKddddddKsK..",
    "..KSSSKKKKSSsK..",
    "..KSSSSKKSSSsK..",
    "..KSSSSKKSSSsK..",
    "...KSSSKKSSsK...",
    "..KKKSSSSSsKKK..",
    ".KGGKKKKKKKKGGK.",
    ".KgGGGGGGGGGGgK.",
    "..KKKKKKKKKKKK..",
  ],
  settings: [
    "......KKKK......",
    "...KK.KiiK.KK...",
    "..KiiKKiiKKiiK..",
    "..KiiiiiiiiiiK..",
    "...KiiSSSSiiK...",
    ".KKKiSKKKKSiKKK.",
    "KiiiiSK..KSiiiiK",
    "KiiiSK....KSiiiK",
    "KiiiSK....KSiiiK",
    "KiiiiSK..KSiiiiK",
    ".KKKiSKKKKSiKKK.",
    "...KiiSSSSiiK...",
    "..KiiiiiiiiiiK..",
    "..KiiKKiiKKiiK..",
    "...KK.KiiK.KK...",
    "......KKKK......",
  ],
  gp: [
    "................",
    ".....KKKKKK.....",
    "...KKYYYGGGKK...",
    "..KYYGGGGGGGgK..",
    "..KYGGKKKKGGgK..",
    ".KYGGKYGGgKGGgK.",
    ".KYGKYGKKKKGGgK.",
    ".KGGKGgKGGGKGgK.",
    ".KGGKGgKKgKKGgK.",
    ".KGGKGggggKGGgK.",
    ".KGGGKKKKKKGggK.",
    "..KGGGGGGGGggK..",
    "..KgGGGGGGgggK..",
    "...KKgggggggK...",
    ".....KKKKKKK....",
    "................",
  ],
  lock: [
    "................",
    ".....KKKKKK.....",
    "....KSiiiiSK....",
    "...KSK....KSK...",
    "...KSK....KSK...",
    "...KSK....KSK...",
    "..KKKKKKKKKKKK..",
    "..KYGGGGGGGGgK..",
    "..KGGGGKKGGGgK..",
    "..KGGGKkkKGGgK..",
    "..KGGGGKKGGGgK..",
    "..KGGGGKKGGGgK..",
    "..KgGGGGGGGGgK..",
    "..KggggggggggK..",
    "..KKKKKKKKKKKK..",
    "................",
  ],
  sword: [
    "..............KK",
    ".............KIK",
    "............KIiK",
    "...........KIiK.",
    "..........KIiK..",
    ".........KIiK...",
    "........KIiK....",
    ".......KIiK.....",
    "..KK..KIiK......",
    "..KGKKIiK.......",
    "...KGIiK........",
    "....KGGK........",
    "...KwKKGK.......",
    "..KwK...KK......",
    ".KGK............",
    ".KK.............",
  ],
  diaries: [
    "................",
    "..KKKKKKKKKKKK..",
    ".KwWWWWWWWWWWwK.",
    ".KwKKKKKKKKKKwK.",
    ".KwKYGGGGGGgKwK.",
    ".KwKGKKKKKKgKwK.",
    ".KwKGKPPPPKgKwK.",
    ".KwKGKKKKKKgKwK.",
    ".KwKYGGGGGGgKwK.",
    ".KwKKKKKKKKKKwK.",
    ".KwWWWWWWWWWWwK.",
    ".KwWWWWWWWWWWwK.",
    ".KKKKKKKKrrKKKK.",
    ".KPPPPPPPrrPPPK.",
    "..KKKKKKKrRKKK..",
    ".........KK.....",
  ],
  gamepad: [
    "................",
    "................",
    "................",
    "...KKKKKKKKKK...",
    "..KSSSSSSSSSSK..",
    ".KSSKSSSSSSRSSK.",
    ".KSKKKSSSSUSMSK.",
    ".KSSKSSSSSSYSSK.",
    ".KSSSSSKKSSSSSK.",
    ".KSSSSKddKSSSSK.",
    ".KSSSKK..KKSSSK.",
    "..KSSK....KSSK..",
    "...KK......KK...",
    "................",
    "................",
    "................",
  ],
  burger: [
    "................",
    "................",
    ".....KKKKKK.....",
    "...KKGYGGYGKK...",
    "..KGGGGYGGGGGK..",
    "..KGGGGGGGGGGK..",
    "..KKKKKKKKKKKK..",
    ".KMMmMMmMMmMMMK.",
    "..KrrrrrrrrrrK..",
    "..KxbbbbbbbbxK..",
    "..KbbbbbbbbbbK..",
    "..KKKKKKKKKKKK..",
    "..KGGGGGGGGGgK..",
    "...KKKKKKKKKK...",
    "................",
    "................",
  ],
  gift: [
    "................",
    "......KKKK......",
    ".....K....K.....",
    ".....K....K.....",
    "...KKKKKKKKKK...",
    "...KRrrrrrrrK...",
    "...KRrrrrrrrK...",
    "...KRrrYYrrrK...",
    "...KRrrYYrrrK...",
    "...KRrrrrrrrK...",
    "...KRrrrrrrrK...",
    "...KRrrrrrrxK...",
    "...KxxxxxxxxK...",
    "...KKKKKKKKKK...",
    "................",
    "................",
  ],
  monitor: [
    "................",
    "................",
    ".KKKKKKKKKKKKKK.",
    ".KddddddddddddK.",
    ".KdcccccccccTdK.",
    ".KdcccccccccTdK.",
    ".KdccccccccccdK.",
    ".KdccccccccccdK.",
    ".KdccccccccccdK.",
    ".KddddddddddddK.",
    ".KKKKKKKKKKKKKK.",
    "......KSSK......",
    "......KSSK......",
    "....KKKKKKKK....",
    "....KLLLLLLK....",
    "....KKKKKKKK....",
  ],
  tent: [
    "................",
    "................",
    ".......KK.......",
    "......KMmK......",
    "......KMmK......",
    ".....KMMmmK.....",
    ".....KMMmmK.....",
    "....KMMMmmmK....",
    "....KMMKKmmK....",
    "...KMMMKkKmmK...",
    "...KMMKkkkKmK...",
    "..KMMMKkkkKmmK..",
    ".KMMMMKkkkKmmmK.",
    "KKKKKKKKKKKKKKKK",
    ".nnnnnnnnnnnnnn.",
    "................",
  ],
  star: [
    "................",
    ".......KK.......",
    "......KYGK......",
    "......KYGK......",
    ".....KYYGgK.....",
    "KKKKKKYYGgKKKKKK",
    "KYYYYYYYGGGGGggK",
    ".KYYYYYYGGGGggK.",
    "..KYYYYYGGGggK..",
    "...KYYYYGGggK...",
    "...KYYYGGGggK...",
    "..KYYYGKKGGggK..",
    "..KYYGK..KGggK..",
    ".KYGK......KGgK.",
    ".KKK........KKK.",
    "................",
  ],
  check: [
    "................",
    ".....KKKKKK.....",
    "...KKmmmmmmKK...",
    "..KKmmmmmmmmKK..",
    "..KmmmmmmmmmmK..",
    ".KmmmmmmmmmPmmK.",
    ".KmmmmmmmmPPmmK.",
    ".KmmmmmmmPPmmmK.",
    ".KmmPPmmPPmmmmK.",
    ".KmmmPPPPmmmmmK.",
    ".KmmmmPPmmmmmmK.",
    "..KmmmmmmmmmmK..",
    "..KKmmmmmmmmKK..",
    "...KKmmmmmmKK...",
    ".....KKKKKK.....",
    "................",
  ],
} as const satisfies Record<string, readonly string[]>;

export type SpriteName = keyof typeof SPRITES;
