/**
 * Questly pixel-art sprite sheet — original artwork, drawn as 16×16 grids.
 * Each character maps to a design-token color in SPRITE_PALETTE; "." is clear.
 * Keep every row exactly 16 characters (enforced by sprites.test.ts).
 */

export const SPRITE_PALETTE: Record<string, string> = {
  K: "var(--color-border-dark)",
  g: "var(--color-gold-600)",
  G: "var(--color-gold-400)",
  Y: "var(--color-gold-200)",
  b: "var(--color-timber-800)",
  w: "var(--color-timber-600)",
  W: "var(--color-timber-500)",
  d: "var(--color-stone-800)",
  s: "var(--color-stone-700)",
  L: "var(--color-stone-600)",
  S: "var(--color-stone-500)",
  i: "var(--color-text-secondary)",
  I: "var(--color-text-primary)",
  p: "var(--color-parchment-200)",
  P: "var(--color-parchment-50)",
  q: "var(--color-parchment-400)",
  k: "var(--color-parchment-ink)",
  m: "var(--color-moss-500)",
  M: "var(--color-moss-300)",
  n: "var(--color-moss-700)",
  t: "var(--color-teal-500)",
  T: "var(--color-teal-300)",
  c: "var(--color-teal-700)",
  r: "var(--color-crimson-500)",
  R: "var(--color-crimson-300)",
  x: "var(--color-crimson-700)",
  u: "var(--color-blue-500)",
  U: "var(--color-blue-300)",
  e: "var(--color-difficulty-master)",
  o: "var(--color-difficulty-grandmaster)",
  "1": "var(--color-skill-creator)",
  "2": "var(--color-skill-business)",
  "3": "var(--color-skill-finance)",
  "4": "var(--color-skill-fitness)",
  "5": "var(--color-skill-home)",
  "6": "var(--color-skill-focus)",
  V: "color-mix(in oklab, var(--color-skill-creator), white 35%)",
  v: "color-mix(in oklab, var(--color-skill-creator), black 35%)",
};

export const SPRITES = {
  // ---------------------------------------------------------------- Skills
  "skill-creator": [
    "KK............KK",
    "KVK..........KVK",
    "K1VK........KV1K",
    ".K11K......K11K.",
    "..K11K....K11K..",
    "...K11K..K11K...",
    "....K1vKKv1K....",
    ".....Kv11vK.....",
    ".....Kv11vK.....",
    "....K1vKKv1K....",
    "...KgGK..KGgK...",
    "..KgGK....KGgK..",
    ".KgGK......KGgK.",
    "KgGK........KGgK",
    "KKK..........KKK",
    "................",
  ],
  "skill-business": [
    "................",
    "................",
    ".....KKKKKK.....",
    "....KbKKKKbK....",
    "....Kb....bK....",
    "KKKKKKKKKKKKKKKK",
    "KUUUUUUUUUUUUUUK",
    "K22222222222222K",
    "K22222KKKK22222K",
    "KKKKKKKYGKKKKKKK",
    "K22222KKKK22222K",
    "K22222222222222K",
    "K22222222222222K",
    "Ku222222222222uK",
    "KKKKKKKKKKKKKKKK",
    "................",
  ],
  "skill-finance": [
    "................",
    ".........KKKKK..",
    "........KYGGGgK.",
    "........KKKKKKK.",
    "........KYGGGgK.",
    "..KKKKK.KKKKKKK.",
    ".KYGGGgKKYGGGgK.",
    ".KKKKKKKKKKKKKK.",
    ".KYGGGgKKYGGGgK.",
    ".KKKKKKKKKKKKKK.",
    ".KYGGGgKKYGGGgK.",
    ".KKKKKKKKKKKKKK.",
    ".KYGGGgKKYGGGgK.",
    ".KgggggKKgggggK.",
    "..KKKKK..KKKKK..",
    "................",
  ],
  "skill-fitness": [
    "................",
    "................",
    "..KKK......KKK..",
    ".KR4K......K4RK.",
    ".KR4K......K4RK.",
    "KKR4KKKKKKKK4RKK",
    "KLR4KiiiiiiK4RLK",
    "KLR4KLLLLLLK4RLK",
    "KKR4KKKKKKKK4RKK",
    ".KR4K......K4RK.",
    ".Kx4K......K4xK.",
    "..KKK......KKK..",
    "................",
    "................",
    "................",
    "................",
  ],
  "skill-home": [
    "...........KKK..",
    ".......KK..KsK..",
    "......KR5K.KsK..",
    ".....KR555KKsK..",
    "....KR55555KsK..",
    "...KR5555555KK..",
    "..KR555555555K..",
    ".KR55555555555K.",
    "KKKKKKKKKKKKKKKK",
    ".KwpppppwppppwK.",
    ".KwKKKppwpKKKwK.",
    ".KwKYKppwpKwKwK.",
    ".KwKKKppwpKwKwK.",
    ".KwpppppwpKwKwK.",
    ".KKKKKKKKKKKKKK.",
    "................",
  ],
  "skill-focus": [
    "................",
    "..KKKK..KKKK....",
    ".K6M66KK6M66K...",
    ".K6666666666K...",
    ".K6666666666K...",
    "..K66666666K....",
    ".K6M66666M66K...",
    ".K6666666666K...",
    ".K66666666n6K...",
    "..KKKK..KKKnK...",
    "...........KnK..",
    "............KnK.",
    ".............KK.",
    "................",
    "................",
    "................",
  ],

  // ------------------------------------------------------------ Navigation
  world: [
    ".....KKKKKK.....",
    "...KKttttttKK...",
    "..KtMMtttttttK..",
    ".KtMMMmtttMMttK.",
    ".KtMMmmtttMmmtK.",
    "KttMmmtttttmmttK",
    "KtttmttttttttttK",
    "KtttttMMMtttttcK",
    "KttttMMmmmttttcK",
    "KttttMmmmmmtttcK",
    "KtttttmmmmttttcK",
    ".KtttttmmtttttK.",
    ".KcttttttttttcK.",
    "..KccttttttccK..",
    "...KKccccccKK...",
    ".....KKKKKK.....",
  ],
  quests: [
    "................",
    "..KKKKKKKKKKKK..",
    ".KqPPPPPPPPPPqK.",
    ".KKKKKKKKKKKKKK.",
    "..KPPPPPPPPPPK..",
    "..KPkkkkkkkPPK..",
    "..KPPPPPPPPPPK..",
    "..KPkkkkkkPPPK..",
    "..KPPPPPPPPPPK..",
    "..KPkkkkkkkkPK..",
    "..KPPPPPPPPPPK..",
    "..KPkkkkkPPrrK..",
    ".KKKKKKKKKKrRK..",
    ".KqPPPPPPPPKrK..",
    "..KKKKKKKKKKK...",
    "................",
  ],
  questlines: [
    "...........KKK..",
    "..........KYGgK.",
    "..........KGGgK.",
    "...........KKK..",
    ".........K.K....",
    "........K..K....",
    "..KKK..K...K....",
    ".KTTtKK....K....",
    ".KTttK....KKK...",
    "..KKK....KMmmK..",
    "...K.....KmmnK..",
    "...K......KKK...",
    "...K............",
    "..KKK...........",
    ".KiiSK..........",
    ".KiSSK..........",
  ],
  skills: [
    ".......KK.......",
    "......KYGK......",
    "......KYGK......",
    ".....KYGGgK.....",
    "KKKKKKYGGgKKKKKK",
    "KYYYYYGGGGGGGggK",
    ".KYGGGGGGGGGggK.",
    "..KGGGGGGGGGgK..",
    "...KGGGGGGGgK...",
    "...KGGGGGGGgK...",
    "..KGGGgKKGGGgK..",
    "..KGGgK..KGGgK..",
    ".KGGgK....KGggK.",
    ".KGgK......KggK.",
    ".KKK........KKK.",
    "................",
  ],
  diaries: [
    "................",
    "..KKKKKKKKKKKK..",
    ".KwWWWWWWWWWWwK.",
    ".KwKKKKKKKKKKwK.",
    ".KwKYGGGGGGgKwK.",
    ".KwKGKKKKKKgKwK.",
    ".KwKGKPPPPKgKwK.",
    ".KwKGKKKKKKgKwK.",
    ".KwKYGGGGGGgKwK.",
    ".KwKKKKKKKKKKwK.",
    ".KwWWWWWWWWWWwK.",
    ".KwWWWWWWWWWWwK.",
    ".KKKKKKKKrrKKKK.",
    ".KPPPPPPPrrPPPK.",
    "..KKKKKKKrRKKK..",
    ".........KK.....",
  ],
  combat: [
    "KK............KK",
    "KIK..........KIK",
    ".KIK........KIK.",
    "..KIK......KIK..",
    "...KIK....KIK...",
    "....KIK..KIK....",
    ".....KIKKIK.....",
    "......KIIK......",
    "......KIIK......",
    ".....KIKKIK.....",
    "..KKKIK..KIKKK..",
    "..KGGKK..KKGGK..",
    "...KwK....KwK...",
    "..KwK......KwK..",
    ".KGK........KGK.",
    ".KK..........KK.",
  ],
  bosses: [
    "KK............KK",
    "KiK..........KiK",
    "KiiK.KKKKKK.KiiK",
    ".KiiKIIIIIIKiiK.",
    "..KKIIIIIIIIKK..",
    "...KIIIIIIIIK...",
    "..KIIIIIIIIIIK..",
    "..KIKKKIIKKKIK..",
    "..KIKrKIIKrKIK..",
    "..KIKKKIIKKKIK..",
    "...KIIIKKIIIK...",
    "....KIIIIIIK....",
    "....KIKIKIKK....",
    "....KKIKIKIK....",
    ".....KKKKKK.....",
    "................",
  ],
  collection: [
    "................",
    "...KKKKKKKKKK...",
    "..KwWWWWWWWWwK..",
    ".KwWWWWWWWWWWwK.",
    ".KGKKKKKKKKKKGK.",
    ".KGwwwwwwwwwwGK.",
    "KKKKKKKKKKKKKKKK",
    "KGgggggKKgggggGK",
    "KwwwwwKYGKwwwwwK",
    "KwwwwwKGgKwwwwwK",
    "KwwwwwwKKwwwwwwK",
    "KGwwwwwwwwwwwwGK",
    "KGbbbbbbbbbbbbGK",
    "KKKKKKKKKKKKKKKK",
    "................",
    "................",
  ],
  shop: [
    "................",
    "......KKKK......",
    ".....KbwwbK.....",
    "......KrrK......",
    ".....KKrrKK.....",
    "....KwWWWWwK....",
    "...KwWWWWWWwK...",
    "..KwWWWKKWWWwK..",
    "..KwWWKYGKWWwK..",
    ".KwWWWKGgKWWWwK.",
    ".KwWWWWKKWWWWwK.",
    ".KwWWWWWWWWWWwK.",
    ".KbwWWWWWWWWwbK.",
    "..KbbwwwwwwbbK..",
    "...KKKKKKKKKK...",
    "................",
  ],
  character: [
    "................",
    ".....KKKKKK.....",
    "....KSiiiiSK....",
    "...KSiSSSSiSK...",
    "..KSiSSSSSSSsK..",
    "..KSSSSSSSSSsK..",
    "..KSKKKKKKKKsK..",
    "..KSKddddddKsK..",
    "..KSSSKKKKSSsK..",
    "..KSSSSKKSSSsK..",
    "..KSSSSKKSSSsK..",
    "...KSSSKKSSsK...",
    "..KKKSSSSSsKKK..",
    ".KGGKKKKKKKKGGK.",
    ".KgGGGGGGGGGGgK.",
    "..KKKKKKKKKKKK..",
  ],
  settings: [
    "......KKKK......",
    "...KK.KiiK.KK...",
    "..KiiKKiiKKiiK..",
    "..KiiiiiiiiiiK..",
    "...KiiSSSSiiK...",
    ".KKKiSKKKKSiKKK.",
    "KiiiiSK..KSiiiiK",
    "KiiiSK....KSiiiK",
    "KiiiSK....KSiiiK",
    "KiiiiSK..KSiiiiK",
    ".KKKiSKKKKSiKKK.",
    "...KiiSSSSiiK...",
    "..KiiiiiiiiiiK..",
    "..KiiKKiiKKiiK..",
    "...KK.KiiK.KK...",
    "......KKKK......",
  ],

  // ----------------------------------------------------- Currency + status
  gp: [
    "................",
    ".....KKKKKK.....",
    "...KKYYYGGGKK...",
    "..KYYGGGGGGGgK..",
    "..KYGGKKKKGGgK..",
    ".KYGGKYGGgKGGgK.",
    ".KYGKYGKKKKGGgK.",
    ".KGGKGgKGGGKGgK.",
    ".KGGKGgKKgKKGgK.",
    ".KGGKGggggKGGgK.",
    ".KGGGKKKKKKGggK.",
    "..KGGGGGGGGggK..",
    "..KgGGGGGGgggK..",
    "...KKgggggggK...",
    ".....KKKKKKK....",
    "................",
  ],
  qp: [
    "................",
    "..KKKKKKKKKKK...",
    ".KqPPPPPPPPPqK..",
    ".KKKKKKKKKKKKK..",
    "..KPPPPPPPPPK...",
    "..KPkkkkkkPPK...",
    "..KPPPPPPPPPK...",
    "..KPkkkkkPPPK...",
    "..KPPPPPPPPPK...",
    "..KPkkkkkkkPK...",
    "..KPPPPPPPPUuK..",
    ".KKKKKKKKKKUuK..",
    ".KqPPPPPPPPKuK..",
    "..KKKKKKKKKKK...",
    "................",
    "................",
  ],
  "combat-points": [
    "KK............KK",
    "KIK..........KIK",
    ".KIK........KIK.",
    "..KIK......KIK..",
    "...KIK....KIK...",
    "....KIK..KIK....",
    ".....KIKKIK.....",
    "......KIIK......",
    "......KIIK......",
    ".....KIKKIK.....",
    "..KKKIK..KIKKK..",
    "..KGGKK..KKGGK..",
    "...KwK....KwK...",
    "..KwK......KwK..",
    ".KGK........KGK.",
    ".KK..........KK.",
  ],
  "total-level": [
    "................",
    "................",
    "..K....KK....K..",
    ".KGK..KYGK..KGK.",
    ".KGGK.KYGK.KGgK.",
    ".KGYGKKGGKKGGgK.",
    ".KGYGGKGGKGGggK.",
    ".KGGYGGGGGGGggK.",
    ".KGGGGGGGGGGggK.",
    ".KgGGrGGuGGtGgK.",
    ".KgGGGGGGGGGggK.",
    ".KKKKKKKKKKKKKK.",
    ".KgggggggggggK..",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
  ],
  lock: [
    "................",
    ".....KKKKKK.....",
    "....KSiiiiSK....",
    "...KSK....KSK...",
    "...KSK....KSK...",
    "...KSK....KSK...",
    "..KKKKKKKKKKKK..",
    "..KYGGGGGGGGgK..",
    "..KGGGGKKGGGgK..",
    "..KGGGKkkKGGgK..",
    "..KGGGGKKGGGgK..",
    "..KGGGGKKGGGgK..",
    "..KgGGGGGGGGgK..",
    "..KggggggggggK..",
    "..KKKKKKKKKKKK..",
    "................",
  ],
  sword: [
    "..............KK",
    ".............KIK",
    "............KIiK",
    "...........KIiK.",
    "..........KIiK..",
    ".........KIiK...",
    "........KIiK....",
    ".......KIiK.....",
    "..KK..KIiK......",
    "..KGKKIiK.......",
    "...KGIiK........",
    "....KGGK........",
    "...KwKKGK.......",
    "..KwK...KK......",
    ".KGK............",
    ".KK.............",
  ],
} as const satisfies Record<string, readonly string[]>;

export type SpriteName = keyof typeof SPRITES;
